### ISSUE TITLE
Option to generate lowercase UUID

### ISSUE THREAD

**Issue by hipwelljo** [JRAppsAU/jrUUID#1]
This generator is super efficient and nifty, thanks! Though using postgres where uppercase support is nil, I am in need of lowercase generated UUIDs. A preferences pane would be nice to hold an option to use lowercase rather than uppercase!

**Comment by joshluongo** [comment]
Hey mate,

Sorry for the very late response, I kinda forgot about this repo. I've uploaded the latest version which now lives in the menu bar and Notification Center. This version now only generates lowercase ids as most of the time this is what is used.
